title: Get started with open source
author: MrKrishnaAgarwal
email: dmkrishna.agarwal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the Journey of becoming an open source contributor

theme: minima

# social links
twitter_username: DMKrishnaA
github_username:  MrKrishnaAgarwal

show_excerpts: true # set to false to remove excerpts on the homepage
